common-settings {
  scala-version = "2.13.16"
}

myproject = [
  {
    dependency = "com.fasterxml.jackson.core:jackson-databind:=2.17.2"
    exclude = ["com.fasterxml.jackson.core:jackson-annotations"]
  }
]

shapes = [
  { dependency = "org.json:json:=20240303", exclude = ["com.google.guava", "org.typelevel::cats-core"] }
]
